/**
 * Renders each caption as a transparent PNG.
 *
 * ffmpeg here is built without libass and without freetype, so neither the
 * `subtitles` nor the `drawtext` filter exists — text has to arrive as pixels.
 * Rendering it in the same browser engine that drew the dashboard also keeps the
 * Korean typography consistent with the frame behind it.
 */
const { chromium } = require('playwright');
const fs = require('fs');

const W = 1080, H = 240;

const BEATS = [
  { id: 'c1', start: 0.0,  end: 2.8,  main: '한 클러스터, 두 팀 — 격리 4축 전부 초록' },
  { id: 'c2', start: 2.8,  end: 5.0,  main: '이 초록이 <em>보장 안 하는 것</em>도 화면에 쓴다' },
  { id: 'c3', start: 5.0,  end: 12.1, main: '경계를 <em>실제로</em> 하나 지운다',
    mono: '$ kubectl delete networkpolicy deny-cross-tenant -n acme-dev-logging' },
  { id: 'c4', start: 12.1, end: 15.2, main: '네 개 중 <b>하나</b> 지웠는데 축이 뒤집힌다', accent: true },
  { id: 'c5', start: 15.2, end: 18.2, main: '이웃 테넌트 globex는 그대로 초록' },
  { id: 'c6', start: 18.2, end: 21.2, main: '되돌린다',
    mono: '$ python scripts/render_tenancy.py acme -e dev | kubectl apply -f -' },
  { id: 'c7', start: 21.2, end: 27.1, main: '레지스트리가 경계를 다시 그린다' },
  { id: 'c8', start: 27.1, end: 30.0, main: '반증되지 않는 화면은 장식이다', closing: true },
];

const NOTE = '실시간 녹화 · 배속 없음 · 푸시 주기 60s→2s (촬영용)';

const page_css = `
  * { margin:0; padding:0; box-sizing:border-box; }
  body { width:${W}px; height:${H}px; background:transparent;
         font-family:'Apple SD Gothic Neo','Helvetica Neue',sans-serif;
         display:flex; flex-direction:column; justify-content:flex-end;
         align-items:center; gap:14px; padding:0 48px 8px; }
  .mono { font-family:'Menlo',monospace; font-size:23px; letter-spacing:-0.2px;
          color:#a9c7ff; background:rgba(9,12,16,0.92); border:1px solid rgba(169,199,255,0.22);
          border-radius:10px; padding:11px 18px; white-space:nowrap; }
  .main { font-size:47px; font-weight:700; letter-spacing:-1px; color:#f2f6fc;
          background:rgba(9,12,16,0.93); border-radius:14px; padding:16px 30px;
          text-align:center; line-height:1.28; }
  .main em { font-style:normal; color:#ffd66e; }
  .main b { color:#ff8a80; }
  .accent { box-shadow:inset 0 0 0 2px rgba(248,81,73,0.55); }
  .closing { background:rgba(9,12,16,0.96); color:#8fd3a8; box-shadow:inset 0 0 0 2px rgba(63,185,80,0.45); }
`;

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: W, height: H } });

  for (const b of BEATS) {
    const cls = `main${b.accent ? ' accent' : ''}${b.closing ? ' closing' : ''}`;
    await page.setContent(
      `<style>${page_css}</style>` +
      (b.mono ? `<div class="mono">${b.mono}</div>` : '') +
      `<div class="${cls}">${b.main}</div>`
    );
    await page.screenshot({ path: `cap-${b.id}.png`, omitBackground: true });
  }

  // Persistent disclosure. Not decoration: the push interval was lowered for the
  // shoot, and a viewer who later measures the real 60s cadence must not find
  // that the video quietly disagreed with the system.
  await page.setViewportSize({ width: W, height: 90 });
  await page.setContent(
    `<style>*{margin:0;padding:0;box-sizing:border-box}
     body{width:${W}px;height:90px;background:transparent;display:flex;
          justify-content:flex-end;align-items:flex-start;padding:22px 26px 0;
          font-family:'Apple SD Gothic Neo',sans-serif}
     .n{font-size:23px;color:#c7d2e0;background:rgba(9,12,16,0.86);
        border:1px solid rgba(255,255,255,0.14);border-radius:8px;padding:9px 15px}</style>
     <div class="n">${NOTE}</div>`
  );
  await page.screenshot({ path: 'cap-note.png', omitBackground: true });

  await browser.close();
  fs.writeFileSync('beats-captions.json', JSON.stringify(BEATS, null, 2));

  // The ffmpeg command is GENERATED from the same BEATS list that produced the
  // images, never hand-maintained beside it: an overlay chain whose enable=
  // windows disagree with the captions they gate is a video that lies about what
  // the screen was doing, and nothing would fail while it did.
  const inputs = ['-ss "$START" -t "$DUR" -i "$RAW"']
    .concat(BEATS.map((b) => `-i cap-${b.id}.png`))
    .concat(['-i cap-note.png', '-f lavfi -t "$DUR" -i anullsrc=channel_layout=stereo:sample_rate=44100']);
  const chain = ['[0:v]crop=768:960:288:8,scale=1080:1350:flags=lanczos,fps=30[base]'];
  let prev = 'base';
  BEATS.forEach((b, i) => {
    const out = `v${i + 1}`;
    chain.push(`[${prev}][${i + 1}:v]overlay=x=0:y=1350-${H}-36:enable='between(t,${b.start},${b.end})'[${out}]`);
    prev = out;
  });
  chain.push(`[${prev}][${BEATS.length + 1}:v]overlay=x=0:y=0[vout]`);

  fs.writeFileSync('build_video.sh', [
    '#!/bin/bash',
    '# GENERATED by render_captions.js — do not edit; change BEATS and re-run.',
    'set -e',
    'RAW=${RAW:-$(ls raw/*.webm)}',
    '# Trim window: baseline_stable .. +30s, read off record_falsification.js beats.',
    'START=${START:-3.7}',
    'DUR=${DUR:-30}',
    'ffmpeg -v warning \\',
    ...inputs.map((i) => `  ${i} \\`),
    `  -filter_complex "${chain.join(';')}" \\`,
    `  -map "[vout]" -map ${BEATS.length + 2}:a \\`,
    '  -c:v libx264 -preset slow -crf 20 -pix_fmt yuv420p -c:a aac -b:a 96k \\',
    '  -movflags +faststart -y isolation-falsified-30s.mp4',
    'echo "wrote isolation-falsified-30s.mp4"',
  ].join('\n') + '\n', { mode: 0o755 });

  console.log('rendered', BEATS.length, 'captions + note, wrote build_video.sh');
})();
