{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-agent.fullname" . }}
  labels:
    {{- include "platform-agent.labels" . | nindent 4 }}
{{- end }}
